#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

test -f $HOME/.Xkeymap && xkbcomp $HOME/.Xkeymap $DISPLAY


export TERMINAL=termite

retina=$(xrandr | grep Screen | grep 2880)

if [ "$retina" != "" ]; then
    $HOME/dotfiles/config/xorg/dpi.sh retina
else
    $HOME/dotfiles/config/xorg/dpi.sh cinema
fi

test -f $HOME/.Xresources.d/$BASE16_THEME && xrdb -merge "$HOME/.Xresources.d/$BASE16_THEME"

exec i3
