rm -f ~/.tmux.conf
rm -rf ~/.config
rm -rf ~/.vim*
rm -f ~/.zprezto
rm -f ~/.dev.tmux.conf
rm -f ~/.zlogin
rm -f ~/.zlogout
rm -f ~/.zprezto
rm -f ~/.zpreztorc
rm -f ~/.zprofile
rm -f ~/.zshenv
rm -f ~/.zshrc
rm -f ~/.tmux*
rm -f ~/.fzf
rm -f $HOME/.zsh-ui-background
rm -f $HOME/.zsh-ui-theme
rm -f $DOTFILES/base16-shell
rm -f $DOTFILES/prezto
